### ISSUE TITLE
Broken genome_tree package

### ISSUE THREAD

**Issue by lmrodriguezr** [Ecogenomics/CheckM#19]
I just downloaded the CheckM data from ACE (`checkm data update`), and the `tree` task is failing with the error message:

```
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 12 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 12 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 12 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 12 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
Uncaught exception: syntax error lexing between line 1 character 0 and line 1 character 1 of /usr/local/opt/checkm/genome_tree/genome_tree_full.refpkg/phylo_modelytLSd6.json
Fatal error: exception Ppatteries.Sparse.Parse_error("syntax error lexing", _, _, _)
Uncaught exception: Sys_error("07.annotation/03.bins/checkm/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("07.annotation/03.bins/checkm/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:00:04.322 || Total: 0:00:04.322 }


```

This seems to be the result of a broken package in `genome_tree/genome_tree_full.refpkg`. The `CONTENTS.json` file has:

```
{
    "files": {
        "aln_fasta": "genome_tree.fasta",
        "phylo_model": "phylo_modelytLSd6.json",
        "tree": "genome_tree.tre",
        "tree_stats": "genome_tree.log"
    },
    "rollback": null,
    "log": [
        "Stripped refpkg (removed 0 files)",
        "Loaded initial files into empty refpkg"
    ],
    "metadata": {
        "create_date": "2015-01-14 09:54:02",
        "format_version": "1.1",
        "locus": "genome_tree_full"
    },
    "rollforward": null,
    "md5": {
        "aln_fasta": "69dada0c0070c7be4983e98ae0142e85",
        "phylo_model": "87c6c85d22b24bd1100d360cd843f75b",
        "tree": "f1b6e14d911cfdfea6af5f9bc0fc5dd7",
        "tree_stats": "8f2fcb7bca5c45632285394aab329908"
    }
}
```

However, the package doesn't contain a `phylo_modelytLSd6.json` file, instead it contains a `phylo_modelytLSd6.json` file, but it has an HTML error instead of the expected JSON data:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /public/CheckM_databases//genome_tree/genome_tree_full.refpkg/phylo_modelytLSd6.json was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at data.ace.uq.edu.au Port 443</address>
</body></html>
```

Is it possible that the data manifest in the ACE server is broken? Or can this be a bug in ScreamingBackpack?

**Comment by lmrodriguezr** [comment]
BTW, I get a similar error with the reduced tree (`-r`), and the `genome_tree/genome_tree_reduced.refpkg` package seems to be broken just like `genome_tree_full.pkg`. The `CONTENTS.json` file lists `phylo_modelJqWx6_.json` as the phylo_model, but the file doesn't exist. Instead, the folder contains `phylo_modelFVIkFz.json`, with the HTML error:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /public/CheckM_databases//genome_tree/genome_tree_reduced.refpkg/phylo_modelFVIkFz.json was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at data.ace.uq.edu.au Port 443</address>
</body></html>
```

**Comment by dparks1134** [comment]
Hello Luis,

I believe this problem has been resolved with the latest update to CheckM (v0.9.7) which occurred on Jan. 16. The files you have indicated were all part of the v0.9.6 release. Did you attempt to update the data recently? Can you give it another try and let me know the results? Much appreciated.

Cheers,
Donovan

**Comment by lmrodriguezr** [comment]
I'm using CheckM v0.9.7, and I ran the update on Jan 19. I just re-ran it and I get the same errors. I also tried removing the data entirely, resetting the root, and re-running the update (a couple of minutes ago), and I still get the same error. Is it possible that there is an erroneous manifest in the server side?

**Comment by dparks1134** [comment]
Correct you are! Thanks! 

I've updated the manifest file. There is a known problem with the robustness of the CheckM updating once the base data is out-of-sync. If using checkm data update still doesn't work, you should be able to fix the problem by downloading the latest CheckM data from:

https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_16012015_v0.9.7.tar.gz

Just decompress it and point CheckM to the new directory with checkm data setRoot.

We are working on making the data updating more robust. I appreciate you bringing these issues to my attention.

**Comment by lmrodriguezr** [comment]
Works like a charm.
Thanks!

**Comment by VeronikaKivenson** [comment]
I was installing checkm on 5/7/17 and ran into a similar problem; with the CONTENTS.json, (logfile below). I ran the checkm data update but it didn't fix this problem. Its running on a cluster, so not a memory problem.  I downloaded the data from the link provided (see below) and it solved the problem and worked when I re-ran the same jobfile. 

Log file when it wasn't working: 
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 28 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 28 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 28 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 28 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
Uncaught exception: Sys_error("/home/kivenson/genome_tree/genome_tree_full.refpkg/CONTENTS.json: No such file or directory")
Fatal error: exception Sys_error("/home/kivenson/genome_tree/genome_tree_full.refpkg/CONTENTS.json: No such file or directory")
Uncaught exception: Sys_error("output_folder/storage/tree/concatenated.pplacer.json: No such file or directory")

Here is the link hat I used to get the genome_tree folder that seems to be the issue (and reset the path to use this instead), and now it works:

https://data.ace.uq.edu.au/public/CheckM_databases checkm_data_16012015_v0.9.7.tar.gz
